x-common-variables: &common-variables
  TZ: ${TZ}
  PUID: ${PUID}
  PGID: ${PGID}

services:
################
# GLUETUN
################
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8085:8085   # qbittorrent
      # - 6881:6881   # Torrent Downloads
      - 8989:8989   # Sonarr
      - 7878:7878   # Radar
      - 9696:9696   # Prowlarr
    environment:
      <<: *common-variables
      VPN_SERVICE_PROVIDER: ${VPN_PROVIDER}
      VPN_TYPE: ${VPN_TYPE}
      WIREGUARD_PRIVATE_KEY: ${WIREGUARD_PRIVATE_KEY}
      SERVER_COUNTRIES: ${SERVER_COUNTRIES}
      VPN_PORT_FORWARDING: "on"
    healthcheck:
      # disable: true
      test: ping -c 1 www.google.com || exit 1
      interval: 120s
      timeout: 20s
      retries: 5
      start_period: 2m
    restart: unless-stopped

################
# RADARR
################

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: "service:gluetun"
    environment:
      <<: *common-variables
    volumes:
      - ${STACK_PATH}/config/radarr:/config
      - ${STACK_PATH}/content/movies:/movies #optional
      - ${STACK_PATH}/downloads:/downloads #optional
    restart: unless-stopped

################
# SONARR
################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: "service:gluetun"
    environment:
      <<: *common-variables
    volumes:
      - ${STACK_PATH}/config/sonarr:/config
      - ${STACK_PATH}/content/tvseries:/tvseries #optional
      - ${STACK_PATH}/downloads:/downloads #optional
    restart: unless-stopped

################
# PROWLARR
################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: "service:gluetun"
    environment:
      <<: *common-variables
    volumes:
      - ${STACK_PATH}/config/prowlarr:/config
    restart: unless-stopped

################
#QBITTORRENT
################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      <<: *common-variables
      WEBUI_PORT: 8085
      TORRENTING_PORT: 6881
    volumes:
      - ${STACK_PATH}/config/qbittorrent:/config
      - ${STACK_PATH}/downloads:/downloads #optional
    restart: unless-stopped

################
#JELLYFIN
################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    network_mode: host
    environment:
      <<: *common-variables
    volumes:
      - ${STACK_PATH}/config/jellyfin:/config
      - ${STACK_PATH}/content/tvseries:/content/tvshows
      - ${STACK_PATH}/content/movies:/content/movies
    restart: unless-stopped