---
services:
################
# GLUETUN
################
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8085:8085   # qbittorrent
      - 6881:6881   # Torrent Downloads
      - 8989:8989   # Sonarr
      - 7878:7878   # Radar
      - 9696:9696   # Prowlarr
      - 50000:50000
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_PROVIDER}
      - VPN_TYPE=${VPN_TYPE}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      #- SERVER_COUNTRIES={SERVER_COUNTRIES}
    healthcheck:
      test: ping -c 1 www.google.com || exit 1
      interval: 60s
      timeout: 20s
      retries: 5
    restart: unless-stopped

################
# RADARR
################

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${STACK_PATH}/config/radarr:/config
      - ${STACK_PATH}/content/movies:/movies #optional
      - ${STACK_PATH}/downloads:/downloads #optional
    network_mode: "service:gluetun"
    restart: unless-stopped

################
# SONARR
################

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${STACK_PATH}/config/sonarr:/config
      - ${STACK_PATH}/content/tvseries:/tvseries #optional
      - ${STACK_PATH}/downloads:/downloads #optional
    network_mode: "service:gluetun"
    restart: unless-stopped

################
# PROWLARR
################

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${STACK_PATH}/config/prowlarr:/config
    network_mode: "service:gluetun"
    restart: unless-stopped

################
#QBITTORRENT
################
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrentcd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - ${STACK_PATH}/config/qbittorrent:/config
      - ${STACK_PATH}/downloads:/downloads #optional
    network_mode: "service:gluetun"
    restart: unless-stopped

################
#JELLYFIN
################
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${STACK_PATH}/config/jellyfin:/config
      - ${STACK_PATH}/content/tvseries:/content/tvshows
      - ${STACK_PATH}/content/movies:/content/movies
    network_mode: host
    restart: unless-stopped